pool:
  vmImage: "Ubuntu 16.04"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "8.12.0"

  - script: npm install

  - script: npx jest --ci --updateSnapshot --reporters=jest-junit --reporters=default --coverage --coverageReporters=cobertura --coverageReporters=html

  - script: npm run build

  - task: PublishTestResults@2
    displayName: "Publish Test Results"
    inputs:
      testResultsFiles: "**/test-*.xml"
      testRunTitle: "test results"

  - task: PublishCodeCoverageResults@1
    displayName: "Publish Test Coverage"
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: "$(System.DefaultWorkingDirectory)/coverage/*coverage.xml"
      reportDirectory: "$(System.DefaultWorkingDirectory)/coverage"

  - task: CopyFiles@2
    displayName: 'Copy builded'
    inputs:
      SourceFolder: '$(agent.builddirectory)'

      Contents: |
      **\*.runsettings
      **\*FunctionalTest*\**\bin\$(BuildConfiguration)\**

      TargetFolder: '$(build.artifactstagingdirectory)\FunctionalTests'

      flattenFolders: true

  - task: CopyFiles@2
    displayName: 'Copy test file'
    inputs:
      SourceFolder: '$(agent.builddirectory)'

      Contents: |
      **\*.runsettings
      **\*FunctionalTest*\**\bin\$(BuildConfiguration)\**

      TargetFolder: '$(build.artifactstagingdirectory)\FunctionalTests'

      flattenFolders: true



  - task: PublishBuildArtifacts@1
  