pool:
  vmImage: "Ubuntu 16.04"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "8.12.0"

  - script: npm install

  - script: npm run test

  - script: npx jest --ci --updateSnapshot --reporters=jest-junit --reporters=default --coverage --coverageReporters=cobertura --coverageReporters=html

  - task: PublishTestResults@2
    displayName: "Publish Test Results"
    inputs:
      testResultsFiles: "**/test-*.xml"
      testRunTitle: "test results"

  - task: PublishCodeCoverageResults@1
    displayName: "Publish Test Coverage"
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: "$(System.DefaultWorkingDirectory)/coverage/*coverage.xml"
      reportDirectory: "$(System.DefaultWorkingDirectory)/coverage"

  - script: npm run build

  - task: ArchiveFiles@2
    displayName: "Archive"
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'
      includeRootFolder: false

  - task: PublishBuildArtifacts@1
  